[general]
altitude = 326.0
port = 8100

[can]
channel = "can0"
interface = "socketcan"

[i2c]
bus = 1

[doorbell]
bell_gpio = 24
button_gpio = 6

[linky]
serial_port = "/dev/ttyAMA0"
baudrate = 9600
bytesize = "SEVENBITS"
parity = "PARITY_EVEN"
stopbits="STOPBITS_ONE"

[ups]
ac220_gpio = 5
buzzer_gpio = 23

[mqtt]
hostname = "localhost"
port = 1883

[logger]
aiohttp = "WARNING"
can = "WARNING"

[logger.domio]
bmp280 = "INFO"
doorbell = "INFO"
linky = "INFO"
ups = "INFO"
