[general]
altitude = 326.0
port = 8085

[database]
path = "/home/domotik/database/domotik.db"

[logger]
aiohttp = "WARNING"
aiosqlite = "WARNING"

[logger.server]
db = "INFO"
graph = "INFO"

[device.doorbell]
type = "event"
trigger = "raising"

[device.pressure]
type = "atmospheric_pressure"
min = 985.0
max = 1035.0

[device.chambre_haut]
type = "humidity_temperature"
temperature_min = 10.0
temperature_max = 30.0
humidity_min = 40.0
humidity_max = 90.0

[device.sejour]
type = "humidity_temperature"
temperature_min = 8.0
temperature_max = 26.0
humidity_min = 40.0
humidity_max = 90.0

[device.outdoor]
type = "humidity_temperature"
temperature_min = -5.0
temperature_max = 45.0
humidity_min = 20.0
humidity_max = 90.0
