[general]
altitude = 326.0
port = 8085

[database]
path = "/home/domotik/database/domotik.db"

[secret]
env_path = "/etc/domotik/server.env"
env_names = [""]

[logger]
aiohttp = "WARNING"
aiosqlite = "WARNING"

[logger.server]
db = "INFO"

[devices]
temperature_humidity = ["sejour", "chambre_haut", "outdoor"]
events = ["doorbell"]

[graph]
pressure_min = 985
pressure_max = 1035
indoor_temperature_min = 10.0
indoor_temperature_max = 28.0
indoor_hygrometry_min = 40.0
indoor_hygrometry_max = 90.0
